import type { BlurbVoice } from "./types.js";

const SOFT_SYLLABLES = ["ba", "bo", "mi", "mu", "na", "no", "wa", "wee", "yip", "mrr"] as const;

const BRIGHT_SYLLABLES = [
  "bip",
  "bop",
  "dii",
  "kiki",
  "mip",
  "nya",
  "pika",
  "twee",
  "wup",
  "zoo",
] as const;

const CLIPPED_SYLLABLES = [
  "dak",
  "dek",
  "gop",
  "ka",
  "ko",
  "tik",
  "tok",
  "vak",
  "zip",
  "hm",
] as const;

const DRY_SYLLABLES = ["brr", "do", "dum", "hm", "mm", "no", "ruh", "vo", "wom", "zun"] as const;

const MINT_SYLLABLES = [
  "mibi",
  "bwo",
  "tik",
  "mwa",
  "nono",
  "pipi",
  "wawa",
  "nup",
  "bwee",
  "mumu",
  "kiki",
  "yip",
] as const;

const PING_SYLLABLES = [
  "pim",
  "billo",
  "pillo",
  "bim",
  "lo",
  "rum",
  "wim",
  "nolla",
  "tup",
  "moro",
  "eh",
  "mm",
] as const;

export const TOKOVO_CAST_VOICES = {
  "teal-manager": {
    id: "teal-manager",
    basePitchHz: 176,
    pitchRangeSemitones: 3.2,
    formantScale: 0.94,
    spectralTilt: 0.58,
    breathiness: 0.04,
    roughness: 0.08,
    electronic: 0.12,
    tempo: 1.08,
    syllables: CLIPPED_SYLLABLES,
    signature: {
      cadenceRegularity: 0.88,
      hesitation: 0.03,
      onsetSalience: 0.68,
      warmth: 0.56,
      pitchMotifSemitones: [0, -0.4, -1.35],
      coarticulation: 0.36,
      vowelDrift: 0.18,
      microVariation: 0.24,
    },
  },
  "coral-intern": {
    id: "coral-intern",
    basePitchHz: 238,
    pitchRangeSemitones: 8.5,
    formantScale: 1.18,
    spectralTilt: 0.38,
    breathiness: 0.08,
    roughness: 0.03,
    electronic: 0.08,
    tempo: 1.24,
    syllables: BRIGHT_SYLLABLES,
    signature: {
      cadenceRegularity: 0.28,
      hesitation: 0.13,
      onsetSalience: 0.82,
      warmth: 0.24,
      pitchMotifSemitones: [0, 2.4, 0.8, 4.2],
      coarticulation: 0.68,
      vowelDrift: 0.54,
      microVariation: 0.58,
    },
  },
  "violet-founder": {
    id: "violet-founder",
    basePitchHz: 132,
    pitchRangeSemitones: 2.1,
    formantScale: 0.84,
    spectralTilt: 0.72,
    breathiness: 0.025,
    roughness: 0.12,
    electronic: 0.05,
    tempo: 0.88,
    syllables: DRY_SYLLABLES,
    signature: {
      cadenceRegularity: 0.94,
      hesitation: 0.01,
      onsetSalience: 0.48,
      warmth: 0.78,
      pitchMotifSemitones: [0, -0.8, -1.65],
      coarticulation: 0.48,
      vowelDrift: 0.15,
      microVariation: 0.18,
    },
  },
  "amber-analyst": {
    id: "amber-analyst",
    basePitchHz: 204,
    pitchRangeSemitones: 5.6,
    formantScale: 1.08,
    spectralTilt: 0.48,
    breathiness: 0.15,
    roughness: 0.035,
    electronic: 0.04,
    tempo: 0.98,
    syllables: SOFT_SYLLABLES,
    signature: {
      cadenceRegularity: 0.52,
      hesitation: 0.42,
      onsetSalience: 0.32,
      warmth: 0.72,
      pitchMotifSemitones: [0, 0.9, 0.25, -0.45],
      coarticulation: 0.74,
      vowelDrift: 0.46,
      microVariation: 0.44,
    },
  },
  "mint-sprite": {
    id: "mint-sprite",
    basePitchHz: 258,
    pitchRangeSemitones: 9,
    formantScale: 1.22,
    spectralTilt: 0.36,
    breathiness: 0.1,
    roughness: 0.025,
    electronic: 0.025,
    tempo: 1.12,
    syllables: MINT_SYLLABLES,
    signature: {
      cadenceRegularity: 0.42,
      hesitation: 0.18,
      onsetSalience: 0.58,
      warmth: 0.43,
      pitchMotifSemitones: [0, 2.8, 1.1, 3.6],
      coarticulation: 0.8,
      vowelDrift: 0.62,
      microVariation: 0.62,
    },
  },
  "ping-courier": {
    id: "ping-courier",
    basePitchHz: 226,
    pitchRangeSemitones: 7.2,
    formantScale: 1.12,
    spectralTilt: 0.44,
    breathiness: 0.06,
    roughness: 0.045,
    electronic: 0.02,
    tempo: 1.16,
    syllables: PING_SYLLABLES,
    signature: {
      cadenceRegularity: 0.58,
      hesitation: 0.14,
      onsetSalience: 0.62,
      warmth: 0.6,
      pitchMotifSemitones: [0, 1.6, 0.4, 2.2],
      coarticulation: 0.82,
      vowelDrift: 0.52,
      microVariation: 0.5,
    },
  },
} as const satisfies Record<string, BlurbVoice>;

export type TokovoCastVoiceId = keyof typeof TOKOVO_CAST_VOICES;

export function getTokovoCastVoice(id: TokovoCastVoiceId): BlurbVoice {
  return TOKOVO_CAST_VOICES[id];
}
