/**
 * Voice Script Types
 *
 * Defines the input format for voice generation scripts.
 * Scripts can be authored by humans or generated by AI (Claude).
 */

// =============================================================================
// SCRIPT TYPES
// =============================================================================

/**
 * Complete voice script for TTS generation
 */
export interface VoiceScript {
  /** Unique identifier for caching and referencing */
  id: string;

  /** Voice assignments: speaker name → provider voice ID */
  voices: Record<string, string>;

  /** Ordered dialogue lines */
  lines: VoiceLine[];

  /** Optional metadata */
  meta?: VoiceScriptMeta;
}

/**
 * Single line of dialogue
 */
export interface VoiceLine {
  /** Speaker identifier (must exist in voices map) */
  speaker: string;

  /** Text with optional emotion tags like [excited], [whispers] */
  text: string;

  /** Optional per-line overrides */
  options?: VoiceLineOptions;
}

/**
 * Per-line options
 */
export interface VoiceLineOptions {
  /** Playback speed hint (0.5-2.0) */
  speed?: number;

  /** Pause after line in milliseconds */
  pause?: number;
}

/**
 * Script metadata
 */
export interface VoiceScriptMeta {
  title?: string;
  description?: string;
  createdAt?: string;
  createdBy?: string; // "human" | "claude" | etc.
}

// =============================================================================
// EMOTION TAGS
// =============================================================================

/**
 * Supported emotion tags for ElevenLabs v3
 * These are placed at the start of text: "[excited] Hello!"
 */
export type EmotionTag =
  | "excited"
  | "calm"
  | "whispers"
  | "shocked"
  | "sarcastic"
  | "dramatic"
  | "laughing"
  | "sighs"
  | "curious"
  | "frustrated";

/**
 * Parse emotion tag from text if present
 */
export function parseEmotionTag(text: string): {
  emotion: EmotionTag | null;
  cleanText: string;
} {
  const match = text.match(/^\[(\w+)\]\s*/);
  if (!match) {
    return { emotion: null, cleanText: text };
  }

  const tag = match[1].toLowerCase() as EmotionTag;
  const validTags: EmotionTag[] = [
    "excited",
    "calm",
    "whispers",
    "shocked",
    "sarcastic",
    "dramatic",
    "laughing",
    "sighs",
    "curious",
    "frustrated",
  ];

  if (validTags.includes(tag)) {
    return { emotion: tag, cleanText: text.slice(match[0].length) };
  }

  return { emotion: null, cleanText: text };
}
